---
apiVersion: v1
kind: Namespace
metadata:
  name: mongo
---
apiVersion: v1
kind: Secret
metadata:
  namespace: mongo
  name: mongodb
type: Opaque
data:
  mongo-root-username: dXNlcg==
  mongo-root-password: bGV0bWVpbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongo
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb # name from the secrets file
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongo-root-password

---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: mongo
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: mongo
data:
  database_url: mongodb # This is the name metadata of the service for mongodb
---
apiVersion: v1
kind: Secret
metadata:
  namespace: mongo
  name: mongo-express
type: Opaque
data:
  mongo-root-username: dXNlcg==
  mongo-root-password: bGV0bWVpbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mongo
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-express # name from the secrets file
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-express
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: database_url

---
# Service
apiVersion: v1
kind: Service
metadata:
  namespace: mongo
  name: mongo-express
spec:
  selector:
    app: mongo-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: mongo
  name: mongo-express
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: mongo-express
              servicePort: 80
